apiVersion: apps/v1
kind: Deployment
metadata:
  name: dk-svc-message
spec:
  selector:
    matchLabels:
      app: dk-svc-message
  template:
    metadata:
      labels:
        app: dk-svc-message
    spec:
      containers:
      - name: dk-svc-message
        image: public.ecr.aws/r8o6w0j4/dk-svc-message:latest
        env:
          - name: SMTP_HOST
            valueFrom:
              configMapKeyRef: 
                name: smtp-configmap
                key: smtp-host
          - name: SMTP_PORT
            valueFrom:
              configMapKeyRef: 
                name: smtp-configmap
                key: smtp-port
          - name: SMTP_USERNAME
            valueFrom:
              secretKeyRef: 
                name: smtp-secret
                key: smtp-username
          - name: SMTP_PASSWORD
            valueFrom:
              secretKeyRef: 
                name: smtp-secret
                key: smtp-password
          - name: ATTACHMENT_SIZE_LIMIT
            valueFrom:
              configMapKeyRef:
                name: svc-general-configmap
                key: max-email-attachment-size
        ports:
        - containerPort: 3004

---

apiVersion: v1
kind: Service
metadata:
  name: dk-svc-message-service
spec:
  selector:
    app: dk-svc-message
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3004
  